{
  imports = [
    ./river.nix
    ./kwm.nix
    ./swaybg.nix
    ./waylock.nix
    ./mako.nix
    ./fuzzel.nix
    ./wob.nix
    ./swayidle.nix
    ./kanshi.nix
    ./screenshot.nix
    ./clipboard.nix
    ./gammastep.nix
    ./foot.nix
    ./firefox.nix
    ./filemanager.nix
  ];
}
