# Replace with the output of:
#   nixos-generate-config --no-filesystems --root /
# on the target machine after first install.
# File systems are generated by ./disk-config.nix (disko).

{ ... }:
{
  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
}
